name: assignment-test

on:
  push:
    tags-ignore:
      - '*'
    branches:
      - '*'

jobs:
  unit-test:
    runs-on: ubuntu-latest
    container: cuaesd/aesd-autotest:24-unit-test
    steps:
      - uses: actions/checkout@v2
      - name: Checkout submodules
        run: git submodule update --init --recursive
      - name: Run unit-test.sh
        run: ./unit-test.sh

  full-test:
    runs-on: ubuntu-latest
    container: cuaesd/aesd-autotest:24-assignment2
    steps:
      - uses: actions/checkout@v2
      - name: Checkout submodules
        run: git submodule update --init --recursive
      - name: Run full-test.sh
        run: ./full-test.sh

